events {}

http {

    upstream bookingService {
        server bookingflow:3000;
    }

    upstream searchService {
        server searchflow:3000;
    }

    upstream authService {
        server authflow:8080;
    }

    server {
        listen 80;

        location /api/users/ {
            proxy_pass http://authService;
        }

        # Booking Flow
        location /api/bookings/ {
            proxy_pass http://bookingService/;
        }

        # Search Flow
        location /api/search/ {
            proxy_pass http://searchService;
        }
    }
}